export const books = [
  { id: "hindi-chai-si-mohobbat", title: "Chai Si Mohobbat", category: "Hindi", price: 349, image: "https://m.media-amazon.com/images/I/71Gn678zNFL._SY466_.jpg" },
  { id: "hindi-chaandpur-ki-chanda", title: "Chaandpur Ki Chanda", category: "Hindi", price: 299, image: "https://m.media-amazon.com/images/I/81m7fSg+wpL._SY466_.jpg" },
  { id: "hindi-mahagatha", title: "MahaGatha", category: "Hindi", price: 249, image: "https://99bookstores.com/cdn/shop/files/A1HSVE8jBLL._SL1500.jpg?v=1720697190&width=533" },
  { id: "hindi-geetanjali", title: "Geetanjali", category: "Hindi", price: 349, image: "https://m.media-amazon.com/images/I/51SJcM3e+1L._SY445_SX342_FMwebp_.jpg" },
  { id: "hindi-do-bailo-ki-katha", title: "Do Bailo Ki Katha", category: "Hindi", price: 349, image: "https://m.media-amazon.com/images/I/51tsT0xYjsL._SY445_SX342_FMwebp_.jpg" },
  { id: "hindi-october-junction", title: "October Junction", category: "Hindi", price: 349, image: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1545068866i/43255476._UX160_.jpg" },
  { id: "kids-new-girl", title: "The New Girl", category: "Kids", price: 199, image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQ5A5p3ignP4vmM6srk7bxS1vjlOZvJheKA4C6zLUw2EOdWb281KgVuXX4xtaIUNmEPYEyQSc2QzYQxuTzjB53qX9B3k3cBR5XT1pdsvvEDyU0Q45TtBEju2yYBI9Prd5MWwhk4nQ&usqp=CAc" },
  { id: "kids-case-closed", title: "Case Closed Mystery in the Mansion", category: "Kids", price: 249, image: "https://m.media-amazon.com/images/I/81HK9JFPNaL._SY466_.jpg" },
  { id: "kids-owl-afraid-dark", title: "The Owl who was Afraid of the Dark", category: "Kids", price: 199, image: "https://m.media-amazon.com/images/I/41Dkwm9D2cL._SY445_SX342_FMwebp_.jpg" },
  { id: "kids-wish-tree", title: "Wish Tree", category: "Kids", price: 199, image: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTYdzn20bk9eOZC7bmGm5PCcaFcA3XCRpflPxho374qzR4OZwrET0d3D04IwzzeQOu6q2Z6VrX7FimlXB8c1NDdiaZz6g5XR2O4ZOrx-YQ&usqp=CAc" },
  { id: "kids-the-gita", title: "The Gita", category: "Kids", price: 199, image: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQx1mJnKjaRNOiHRbI4-9AKY5BJlLz8OGXpGnYBkd6y58fAbZB0KaSqpEJzJre-eWaX-xr3NvjWhCHS0ETYgwQK8SEN7ed7cm9wxZSeAPsg&usqp=CAc" },
  { id: "kids-agatha-oddly-secret-key", title: "Agatha Oddly The Secret Key", category: "Kids", price: 199, image: "https://m.media-amazon.com/images/I/51SGfpyA6hL._SY445_SX342_FMwebp_.jpg" },
  { id: "romance-sam", title: "You Have Reached Sam", category: "Romance", price: 299, image: "https://m.media-amazon.com/images/I/51ejN5YB8pL._SY445_SX342_FMwebp_.jpg" },
  { id: "romance-once-youre-mine", title: "Once You're Mine", category: "Romance", price: 299, image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcR72PkTvjZ5tpTy95Y6F86izYiRQDiZsU-Vgq_cD4atIBFea9Facdy7uwDT6aKQmPyBUJii7GFQOaA8j2pFSkqJJ3giHuHk6fPFb3554nAKBKvJiJI0LOWxyNNHQA&usqp=CAc" },
  { id: "romance-love-edits-extra-cheese", title: "Love Edits and Extra Cheese", category: "Romance", price: 299, image: "https://m.media-amazon.com/images/I/41xXrXNjG-L._SY445_SX342_FMwebp_.jpg" },
  { id: "romance-eternal-love", title: "Eternal Love", category: "Romance", price: 299, image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRJ9YXulODXD9oXKytflbjA6SnXqdYThH1iTjFzS0FlQS1jBya1aFE03QT_OjH5Rg1JG9XoOKCjSE5Us8lFUAlsytbAF8gaNY9tSsFRJPxjf0LRMeFu7Np8&usqp=CAc" },
  { id: "romance-all-i-ever-want-is-you", title: "All I ever Want is You", category: "Romance", price: 299, image: "https://m.media-amazon.com/images/I/41-Aq8V3+RL._SY445_SX342_FMwebp_.jpg" },
  { id: "romance-the-thing-called-love", title: "The Thing called Love", category: "Romance", price: 299, image: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSJOQ12jfu4C71IgL_XqCibpbU_GP5MWPpmrS6fnd1idpeLc_kllAg3oTkFLDoXKktAGn8_9qG911NI1yrsZ2ci5CGWAY09tK-jS8avicjBNaafBQ6TeRRMP20CiTdI9G5fIqkIQQ&usqp=CAc" },
  { id: "non-fiction-wings-of-fire", title: "Wings Of Fire", category: "Non Fiction", price: 399, image: "https://m.media-amazon.com/images/I/416dFscW04L._SY445_SX342_FMwebp_.jpg" },
  { id: "non-fiction-living-remedy", title: "A Living Remedy", category: "Non Fiction", price: 299, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR82FlUAgL9Z_ukaHen-qxtUJm1BvwiLUqWAw&s" },
  { id: "non-fiction-stop-wishing-start-creating", title: "Stop Wishing Start Creating", category: "Non Fiction", price: 399, image: "https://miblart.com/wp-content/uploads/2020/11/Stop-Wishing-Start-Creating-1-682x1024.jpg" },
  { id: "non-fiction-sunsets-with-annie", title: "Sunsets With Annie", category: "Non Fiction", price: 399, image: "https://marketplace.canva.com/EADaoD6OqWY/1/0/1003w/canva-sunset-romance-e-book-cover-049KKNST1JA.jpg" },
  { id: "non-fiction-ratan-tata-a-life", title: "Ratan Tata A Life", category: "Non Fiction", price: 399, image: "https://m.media-amazon.com/images/I/719oHU9kiFL._SY466_.jpg" },
  { id: "non-fiction-lifes-amazing-secret", title: "Life's Amazing Secret", category: "Non Fiction", price: 399, image: "https://m.media-amazon.com/images/I/41S8TQ9aNoL._SY445_SX342_FMwebp_.jpg" },
  { id: "business-shark-tank", title: "Shark Tank India", category: "Business", price: 499, image: "https://m.media-amazon.com/images/I/519KVBbmfCL._SY466_.jpg" },
  { id: "business-you-can-win", title: "You Can Win", category: "Business", price: 499, image: "https://m.media-amazon.com/images/I/71KCBR2XkhL._SY466_.jpg" },
  { id: "business-think-and-grow-rich", title: "Think and Grow Rich", category: "Business", price: 499, image: "https://m.media-amazon.com/images/I/61IxJuRI39L._SY425_.jpg" },
  { id: "business-big-bull-of-dalal-street", title: "Big Bull Of Dalal Street", category: "Business", price: 499, image: "https://m.media-amazon.com/images/I/7106FkmlRtL._SY466_.jpg" },
  { id: "business-doglapan", title: "Doglapan", category: "Business", price: 499, image: "https://m.media-amazon.com/images/I/81InFh0R4UL._SY466_.jpg" },
  { id: "business-the-ai-driven-leader", title: "The AI-Driven Leader", category: "Business", price: 499, image: "https://m.media-amazon.com/images/I/41R98ZqSh0L._SY445_SX342_FMwebp_.jpg" }
];
